#!/usr/bin/env python3
"""
gen_m2_wtbl.py -- S7-SIDE30 (DEC-S7-SIDE30-01 (2)(4)): generate the NON-frozen runtime-selectable
weight tables for M2_WTBL_SEL  ->  sprint6/dsp/audio/m1_cces_project/src/m2_wtbl_q15.h

Rows (sel = row + 1; sel 0 is ALWAYS the frozen g_dolph_w8_q15 = Dolph -20, not duplicated here):
    sel 1 = Dolph-Chebyshev -25 dB, sel 2 = -30 dB, sel 3 = -35 dB   (N=16, 8 centre-symmetric pairs)

Iron rule 7 (dual track), same discipline as the frozen table's generator sprint4/dsp/fira/gen_dolph_w8.py:
    track 1 = scipy.signal.windows.chebwin(16, sll) / max
    track 2 = Barbiere/Stegen closed-form Dolph synthesis (factorials only; re-implemented here with the SLL
              as a parameter, same formula as gen_dolph_w8.py:track2_recurrence(), which is hard-wired to 20 dB)
    Q15 = round(w * 32768) (1.0 -> 32768, same scale/container as DOLPH_W8_ONE). Tracks must agree bit-exactly.
ANCHOR (runs first, SystemExit on failure): this generator reproduces the FROZEN D20 Q15 table bit-exactly.
GAP-SAT premise: every value <= 32768 (<= 1.0), centre = 32768.
L-grade: tables [L2/dual-track desktop]; metrics [L2 ideal far-field isotropic model] (s7_common.py).
Usage:  /usr/bin/python3 gen_m2_wtbl.py [--check]   (--check = regenerate in memory and diff against the header)
"""
import os
import re
import sys
from math import factorial

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, os.path.join(REPO, "sprint7", "sim", "acoustic"))
import s7_common as S  # noqa: E402

FROZEN_H = os.path.join(REPO, "sprint4", "dsp", "fira", "dolph_w8_q15.h")
OUT_H = os.path.join(REPO, "sprint6", "dsp", "audio", "m1_cces_project", "src", "m2_wtbl_q15.h")
SLLS = [25.0, 30.0, 35.0]
N = 16
M = N // 2


def track1(sll):
    from scipy.signal.windows import chebwin
    w = chebwin(N, sll)
    return (w / w.max())[:M]                       # edge (c=0) .. centre (c=7)


def track2(sll):
    R = 10.0 ** (sll / 20.0)
    x0 = np.cosh(np.arccosh(R) / (N - 1))
    a = np.zeros(M)
    for n in range(1, M + 1):
        s = 0.0
        for q in range(n, M + 1):
            s += ((-1) ** (M - q)) * factorial(q + M - 2) * (x0 ** (2 * q - 1)) / (
                factorial(q - n) * factorial(q + n - 1) * factorial(M - q))
        a[n - 1] = s
    w8 = np.abs(a[::-1])
    return w8 / w8.max()


def q15(w):
    q = np.round(np.asarray(w) * 32768.0).astype(np.int64)
    assert q.max() <= 32768 and q.min() >= 0
    return q


def frozen_d20():
    t = open(FROZEN_H, encoding="utf-8").read()
    body = t[t.index("g_dolph_w8_q15[DOLPH_W8_NCH] = {"):]
    body = body[body.index("{") + 1: body.index("};")]
    vals = [int(m) for m in re.findall(r"^\s*(\d+),", body, flags=re.M)]
    assert len(vals) == 8, vals
    return np.array(vals, dtype=np.int64)


def metrics(q8):
    w16 = S.expand16(np.asarray(q8, float) / 32768.0)
    ref = S.expand16(frozen_d20().astype(float) / 32768.0)

    def band_att90(fc):
        fs = np.geomspace(fc * 2 ** (-1 / 6), fc * 2 ** (1 / 6), 41)
        p0 = np.mean([abs(S.af_complex([0.0], f, w16)[0]) ** 2 for f in fs])
        p9 = np.mean([abs(S.af_complex([90.0], f, w16)[0]) ** 2 for f in fs])
        return 10 * np.log10(p0 / p9)
    P1k = S.pattern_db(1000.0, w16)
    return {
        "BW1k": S.bw_full(P1k), "SLL": S.peak_sll_interior(P1k),
        "att30_500": S.att_db(30.0, 500.0, w16), "att30_1k": S.att_db(30.0, 1000.0, w16),
        "att90b_1k": band_att90(1000.0), "att90b_2k": band_att90(2000.0), "att90b_4k": band_att90(4000.0),
        "onaxis_vs_d20_dB": 20 * np.log10(w16.sum() / ref.sum()), "WNGn": S.wng_norm_db(w16),
    }


def build():
    S.assert_anchors(verbose=False)
    fz = frozen_d20()
    g20_1, g20_2 = q15(track1(20.0)), q15(track2(20.0))
    if not (np.array_equal(g20_1, fz) and np.array_equal(g20_2, fz)):
        raise SystemExit(f"ANCHOR FAIL: generator D20 {g20_1.tolist()} / {g20_2.tolist()} != frozen {fz.tolist()}")
    rows = []
    for sll in SLLS:
        a, b = q15(track1(sll)), q15(track2(sll))
        if not np.array_equal(a, b):
            raise SystemExit(f"DUAL-TRACK FAIL at {sll} dB: scipy {a.tolist()} vs closed-form {b.tolist()}")
        if a[-1] != 32768:
            raise SystemExit(f"centre weight != 32768 at {sll} dB")
        rows.append((sll, a, metrics(a)))
    return fz, rows


def render(fz, rows):
    fm = metrics(fz)
    L = []
    L.append("/**")
    L.append(" * @file    m2_wtbl_q15.h")
    L.append(" * @brief   S7-SIDE30: runtime-selectable broadside weight tables for M2_WTBL_SEL (NOT frozen).")
    L.append(" *")
    L.append(" * GENERATED by sprint7/dsp/wtbl/gen_m2_wtbl.py -- DO NOT EDIT BY HAND (same-source discipline;")
    L.append(" * `gen_m2_wtbl.py --check` diffs this file against a fresh generation).")
    L.append(" * Basis: DEC-S7-SIDE30-01 (2)(4) (CTO 2026-09-26 agreed to reopen D6 and to firmware changes; that THIS")
    L.append(" *        package falls under it is a PM reading pending CTO review, DEC (4)) and")
    L.append(" *        sprint7/docs/S7_SIDE30_ANALYSIS.md sec 3. Used ONLY under #ifdef M2_WTBL_SEL.")
    L.append(" *")
    L.append(" * sel 0 = the FROZEN g_dolph_w8_q15 (Dolph -20, sprint4/dsp/fira/dolph_w8_q15.h) -- NOT duplicated here.")
    L.append(" * sel k (k=1..M2_WTBL_NEXTRA) = g_m2_wtbl_q15[k-1]. Index c = channel = pair {c,15-c}, edge(0)->centre(7),")
    L.append(" * exactly like the frozen table. Q15 scale 1.0 = 32768 (== DOLPH_W8_ONE); all values <= 32768 (GAP-SAT ok).")
    L.append(" * Dual track (iron rule 7): scipy chebwin vs Barbiere closed form -> bit-identical Q15; generator anchor:")
    L.append(" * reproduces the frozen D20 table bit-exactly. [L2/dual-track desktop]")
    L.append(" *")
    L.append(" * Ideal far-field metrics [L2, isotropic point-source model s7_common.py; NOT board/acoustic readings]:")
    L.append(" *   table  BW(-6)@1k  SLL    att30@500  att30@1k  att90 band-avg 1k/2k/4k   on-axis vs D20  WNGn")

    def row(name, m):
        return (f" *   {name:5s}  {m['BW1k']:6.2f} deg {m['SLL']:6.2f}  {m['att30_500']:6.2f}   {m['att30_1k']:6.2f}   "
                f"{m['att90b_1k']:5.1f}/{m['att90b_2k']:5.1f}/{m['att90b_4k']:5.1f}   {m['onaxis_vs_d20_dB']:+6.2f} dB  "
                f"{m['WNGn']:+5.2f}")
    L.append(row("D20*", fm))
    for sll, _, m in rows:
        L.append(row(f"D{int(sll)}", m))
    L.append(" *   (* D20 = frozen sel 0, listed for reference only)")
    L.append(" * GATING (critic R2 MAJOR-3b): on-board A/B only AFTER polarity QA has measured the channel->position")
    L.append(" * map and the CTO D8 ruling; a deeper table on a mis-mapped array tells you nothing. Table choice waits")
    L.append(" * for the per-driver spread measurement (critic R2 MAJOR-3c).")
    L.append(" */")
    L.append("#ifndef ITC_M2_WTBL_Q15_H")
    L.append("#define ITC_M2_WTBL_Q15_H")
    L.append("")
    L.append("#include <stdint.h>")
    L.append("")
    L.append(f"#define M2_WTBL_NEXTRA  {len(rows)}   /* extra tables beyond the frozen sel-0 table */")
    L.append("")
    L.append("static const int32_t g_m2_wtbl_q15[M2_WTBL_NEXTRA][8] = {")
    for k, (sll, q, _m) in enumerate(rows):
        L.append(f"    {{ {', '.join(f'{v:5d}' for v in q)} }},   /* sel {k + 1}: Dolph-Chebyshev -{int(sll)} dB */")
    L.append("};")
    L.append("")
    L.append("#endif /* ITC_M2_WTBL_Q15_H */")
    return "\n".join(L) + "\n"


def main():
    fz, rows = build()
    txt = render(fz, rows)
    if "--check" in sys.argv:
        cur = open(OUT_H, encoding="utf-8").read()
        if cur != txt:
            raise SystemExit("CHECK FAIL: m2_wtbl_q15.h differs from a fresh generation")
        print("CHECK PASS: m2_wtbl_q15.h == fresh generation")
    else:
        open(OUT_H, "w", encoding="utf-8").write(txt)
        print("wrote", OUT_H)
    print("anchor: generator D20 == frozen", fz.tolist())
    for sll, q, m in rows:
        print(f"D{int(sll)}  Q15 {q.tolist()}  " + "  ".join(f"{k}={v:.3f}" for k, v in m.items()))


if __name__ == "__main__":
    main()
