#!/usr/bin/env python3
"""
make_fira_tree_probe.py -- regenerate sprint7/dsp/probe/fira_tree_probe.c from the FROZEN
sprint4/dsp/fira/fira_tree.c by INSERTING (never editing) S7-tagged bracket lines.

Same-source discipline (S7_B63_WALLCLOCK_GAP.md sec 2.4 / README sec 4):
  * The copy is DIAGNOSTIC ONLY. It never enters a product build. It is linked INSTEAD OF the frozen
    fira_tree.c in the bench project only when the inner split (task/spin/flush/postscale/mem/core) is wanted.
  * Every inserted line carries the token  S7P .  Stripping all lines that contain S7P MUST give back the
    frozen file byte-for-byte (md5 recorded in README; run_s7_probe_guard_check.sh enforces it).
  * If the frozen fira_tree.c ever changes (md5 drift), this script must be re-run (or the copy deleted).

Usage:  /usr/bin/python3 make_fira_tree_probe.py  [--check]
  default: (re)write ../fira_tree_probe.c and print the frozen md5 + insertion count
  --check: only verify that the existing copy strips back to the frozen file (exit 1 on drift)
"""
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))       # repo root
FROZEN = os.path.join(ROOT, "sprint4", "dsp", "fira", "fira_tree.c")
OUT = os.path.normpath(os.path.join(HERE, "..", "fira_tree_probe.c"))
TAG = "S7P"


def md5_of(data: bytes) -> str:
    return hashlib.md5(data).hexdigest()


def find_first(lines, needle, start=0):
    """index of the first line whose rstrip('\\n') == needle at/after start; raise if absent."""
    for i in range(start, len(lines)):
        if lines[i].rstrip("\n") == needle:
            return i
    raise SystemExit(f"anchor not found: {needle!r} (from line {start + 1}) -- frozen file drifted?")


def find_func(lines, signature_prefix):
    for i, l in enumerate(lines):
        if l.startswith(signature_prefix):
            return i
    raise SystemExit(f"function not found: {signature_prefix!r}")


BANNER = [
    "/* S7P ================================================================================== */",
    "/* S7P  DIAGNOSTIC COPY of the FROZEN sprint4/dsp/fira/fira_tree.c -- NOT a product file.     */",
    "/* S7P  Generated by sprint7/dsp/probe/tools/make_fira_tree_probe.py (insert-only; every added  */",
    "/* S7P  line carries the token S7P; stripping those lines yields the frozen file byte-for-byte,  */",
    "/* S7P  md5 recorded in sprint7/dsp/probe/README.md and enforced by run_s7_probe_guard_check.sh). */",
    "/* S7P  PURPOSE: WO-S7-B6.3 inner wall-clock split of one FIRA segment: task (CreateTask+         */",
    "/* S7P  FixedPointEnable+QueueTask) / spin (QueueTask return -> ALL_CHANNEL_DONE seen) / flush   */",
    "/* S7P  (flush_data_buffer) / postscale / mem (history prepend, zero-stuff, history update) /    */",
    "/* S7P  core (detail subtract, sat_add). Brackets are active ONLY with -DS7_PROBE_INNER; without   */",
    "/* S7P  it this file compiles to the same code as the frozen original (tag lines are comments or  */",
    "/* S7P  preprocessed away). NEVER link this file together with fira_tree.c (same symbols):       */",
    "/* S7P  Exclude-from-Build fira_tree.c in the bench project when this copy is in the source list. */",
    "/* S7P  FG (README sec 4): with this copy linked, F4 anchor 0x2E0D8C6E (g_fira_f4_pass) and the   */",
    "/* S7P  F5 eight anchors (g_f5_pass_all) and the probe's g_s7_fg_pass_all MUST still PASS.        */",
    "/* S7P  Diagnostic only; sync (re-run the generator) or DELETE when the frozen file changes.      */",
    "/* S7P ================================================================================== */",
]

GLOBALS = [
    "#ifdef S7_PROBE_INNER                                                      /* S7P */",
    "/* S7P: inner split accumulators (reset per frame by s7_wallclock_probe.c; raw cycle sums only -- C9). */",
    "volatile uint32_t g_s7_in_task_cyc  = 0u;   /* S7P CreateTask + FixedPointEnable + QueueTask (call returns) */",
    "volatile uint32_t g_s7_in_spin_cyc  = 0u;   /* S7P QueueTask return -> ALL_CHANNEL_DONE observed (busy-wait) */",
    "volatile uint32_t g_s7_in_flush_cyc = 0u;   /* S7P flush_data_buffer over the FIRA output span */",
    "volatile uint32_t g_s7_in_post_cyc  = 0u;   /* S7P fira_postscale (80-bit reassemble, >>15, x2, sw decimate, sat) */",
    "volatile uint32_t g_s7_in_mem_cyc   = 0u;   /* S7P history prepend / zero-stuff / history update (memcpy/memmove) */",
    "volatile uint32_t g_s7_in_core_cyc  = 0u;   /* S7P core-side detail subtract (analyze) / sat_add (synthesize) loops */",
    "volatile uint32_t g_s7_in_reads     = 0u;   /* S7P number of inner bench_cyc_target() reads issued */",
    "extern uint32_t bench_cyc_target(void);     /* S7P CCLK cycles == clock() (bench_main.c:118) */",
    "#define S7P_T(v)          do { (v) = bench_cyc_target(); g_s7_in_reads++; } while (0)   /* S7P */",
    "#define S7P_ACC(a, f, t)  do { (a) += (t) - (f); } while (0)                              /* S7P */",
    "#endif                                                                     /* S7P */",
]


def ifd(body):
    """wrap statement lines in #ifdef S7_PROBE_INNER (all lines tagged)."""
    return ["#ifdef S7_PROBE_INNER /* S7P */"] + [b + " /* S7P */" for b in body] + ["#endif /* S7P */"]


def ifd_core(body):
    return ["#if defined(S7_PROBE_INNER) && defined(FIRA_USE_REAL_ADI_FIR_HEADER) /* S7P */"] + \
           [b + " /* S7P */" for b in body] + ["#endif /* S7P */"]


def plan(L):
    """Return the insertion list [(index, [lines])] against the frozen line list L (anchor-based)."""
    ins = []
    # 0. banner before line 1
    ins.append((0, BANNER))
    # 1. globals after the single '#include <stdint.h>'
    i = find_first(L, "#include <stdint.h>")
    ins.append((i + 1, GLOBALS))
    # 2. fira_run_segment: decl / task open / task close+spin open / spin close+flush open / flush close+post open / post close
    fs = find_func(L, "int fira_run_segment(FiraSegKind kind")
    i = find_first(L, "    ADI_FIR_RESULT r;", fs)
    ins.append((i + 1, ifd(["    uint32_t s7_t0 = 0u, s7_t1 = 0u;"])))
    i = find_first(L, "    r = adi_fir_CreateTask(s_hFir, &ch, 1u, (void *)s_taskMem,", fs)
    ins.append((i, ifd(["    S7P_T(s7_t0);                                   /* task bracket OPEN */"])))
    i = find_first(L, "    r = adi_fir_QueueTask(hTask);                           if (r != ADI_FIR_RESULT_SUCCESS) return 5;", fs)
    ins.append((i + 1, ifd(["    S7P_T(s7_t1); S7P_ACC(g_s7_in_task_cyc, s7_t0, s7_t1); s7_t0 = s7_t1;   /* task CLOSE / spin OPEN */"])))
    i = find_first(L, "    while (g_FIRTaskDoneCount < 1u) { /* spin; bench can switch to idle/event wait */ }", fs)
    ins.append((i + 1, ifd(["    S7P_T(s7_t1); S7P_ACC(g_s7_in_spin_cyc, s7_t0, s7_t1); s7_t0 = s7_t1;   /* spin CLOSE / flush OPEN */"])))
    i = find_first(L, "                      1 /*enInv: also invalidate after (no dirty lines under approach B)*/);", fs)
    ins.append((i + 1, ifd(["    S7P_T(s7_t1); S7P_ACC(g_s7_in_flush_cyc, s7_t0, s7_t1); s7_t0 = s7_t1;  /* flush CLOSE / postscale OPEN */"])))
    i = find_first(L, "    (void)fira_postscale(s_seg_out3, fira_window, out_q31, post_ratio, post_phase, kind);", fs)
    ins.append((i + 1, ifd(["    S7P_T(s7_t1); S7P_ACC(g_s7_in_post_cyc, s7_t0, s7_t1);                 /* postscale CLOSE */"])))
    # 3. fira_run_segment_stateful: mem brackets (DEC prepend / DEC hist update / INT prepend+stuff / INT hist update)
    fs = find_func(L, "static int fira_run_segment_stateful(")
    i = find_first(L, "    int rc;", fs)
    ins.append((i + 1, ifd(["    uint32_t s7_m0 = 0u, s7_m1 = 0u;"])))
    i = find_first(L, "        memcpy(s_seg_in, ch->hist[seg_idx], FIRA_HIST * sizeof(int32_t));      /* prepend raw history */", fs)
    ins.append((i, ifd(["        S7P_T(s7_m0);                               /* mem OPEN (DEC prepend) */"])))
    i = find_first(L, "        memcpy(s_seg_in + FIRA_HIST, frame_in, n_frame * sizeof(int32_t));     /* append raw frame */", fs)
    ins.append((i + 1, ifd(["        S7P_T(s7_m1); S7P_ACC(g_s7_in_mem_cyc, s7_m0, s7_m1);   /* mem CLOSE */"])))
    i = find_first(L, "        /* update raw history: last FIRA_HIST raw frame samples */", fs)
    ins.append((i, ifd(["        S7P_T(s7_m0);                               /* mem OPEN (DEC hist update) */"])))
    i = find_first(L, "            memcpy(ch->hist[seg_idx] + keep, frame_in, n_frame * sizeof(int32_t));", fs)
    assert L[i + 1].rstrip("\n") == "        }", "DEC hist-update block end drifted"
    ins.append((i + 2, ifd(["        S7P_T(s7_m1); S7P_ACC(g_s7_in_mem_cyc, s7_m0, s7_m1);   /* mem CLOSE */"])))
    i = find_first(L, "        memcpy(s_seg_in, ch->hist[seg_idx], FIRA_HIST * sizeof(int32_t));", fs)
    ins.append((i, ifd(["        S7P_T(s7_m0);                               /* mem OPEN (INT prepend + zero-stuff) */"])))
    i = find_first(L, "            s_seg_in[FIRA_HIST + (uint32_t)i * 2u + 1u] = 0;", fs)
    assert L[i + 1].rstrip("\n") == "        }", "INT zero-stuff loop end drifted"
    ins.append((i + 2, ifd(["        S7P_T(s7_m1); S7P_ACC(g_s7_in_mem_cyc, s7_m0, s7_m1);   /* mem CLOSE */"])))
    i = find_first(L, "        /* update zero-stuffed history: last FIRA_HIST samples of [history ++ zero_stuffed_frame].", fs)
    ins.append((i, ifd(["        S7P_T(s7_m0);                               /* mem OPEN (INT hist update) */"])))
    i = find_first(L, "            memcpy(ch->hist[seg_idx] + keep, &s_seg_in[FIRA_HIST], zlen * sizeof(int32_t));", fs)
    assert L[i + 1].rstrip("\n") == "        }", "INT hist-update block end drifted"
    ins.append((i + 2, ifd(["        S7P_T(s7_m1); S7P_ACC(g_s7_in_mem_cyc, s7_m0, s7_m1);   /* mem CLOSE */"])))
    # 4. fira_tfb_analyze: core-side detail subtract
    fs = find_func(L, "void fira_tfb_analyze(")
    i = find_first(L, "    uint16_t i;", fs)
    ins.append((i + 1, ifd_core(["    uint32_t s7_c0 = 0u, s7_c1 = 0u;"])))
    i = find_first(L, "    /* -- core-side (FIRA has no vector sub): detail = this level - interp2(lower level) -- */", fs)
    ins.append((i, ifd_core(["    S7P_T(s7_c0);                                   /* core OPEN (detail subtract) */"])))
    i = find_first(L, "    for (i = 0u; i < f3; i++) sb0[i] = a3[i];           /* SB0 coarse @f3 (:164) */", fs)
    ins.append((i + 1, ifd_core(["    S7P_T(s7_c1); S7P_ACC(g_s7_in_core_cyc, s7_c0, s7_c1);   /* core CLOSE */"])))
    # 5. fira_tfb_synthesize: the three sat_add loops
    fs = find_func(L, "void fira_tfb_synthesize(")
    i = find_first(L, "    uint16_t i;", fs)
    ins.append((i + 1, ifd_core(["    uint32_t s7_c0 = 0u, s7_c1 = 0u;"])))
    for anchor in (
        "    for (i = 0u; i < f2; i++) a2p[i] = f_sat_add_i32(up3[i], sb1[i]);   /* bit-identical tree_filterbank.c:197 */",
        "    for (i = 0u; i < f1; i++) a1p[i] = f_sat_add_i32(up2[i], sb2[i]);   /* :201 */",
        "    for (i = 0u; i < f0; i++) out[i] = f_sat_add_i32(up1[i], sb3[i]);   /* :205 */",
    ):
        i = find_first(L, anchor, fs)
        ins.append((i, ifd_core(["    S7P_T(s7_c0);                                   /* core OPEN (sat_add) */"])))
        ins.append((i + 1, ifd_core(["    S7P_T(s7_c1); S7P_ACC(g_s7_in_core_cyc, s7_c0, s7_c1);   /* core CLOSE */"])))
    return ins


def merge(L, ins):
    """Insert blocks bottom-up; blocks sharing an index keep the order in which plan() added them."""
    groups = {}
    for idx, block in ins:
        groups.setdefault(idx, []).extend(block)
    out = list(L)
    for idx in sorted(groups.keys(), reverse=True):
        out[idx:idx] = [b + "\n" for b in groups[idx]]
    return out


def main():
    check_only = "--check" in sys.argv
    with open(FROZEN, "rb") as f:
        frozen_bytes = f.read()
    frozen_md5 = md5_of(frozen_bytes)
    frozen_lines = frozen_bytes.decode("utf-8").splitlines(keepends=True)
    if any(TAG in l for l in frozen_lines):
        raise SystemExit("frozen fira_tree.c already contains the tag S7P -- generator cannot be applied safely")

    if not check_only:
        ins = plan(frozen_lines)          # raises on anchor drift
        out = merge(frozen_lines, ins)
        with open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.writelines(out)
        print(f"[make_fira_tree_probe] frozen md5 {frozen_md5}  insert-blocks {len(ins)}  -> {os.path.relpath(OUT, ROOT)}")

    with open(OUT, "rb") as f:
        copy_bytes = f.read()
    copy_lines = copy_bytes.decode("utf-8").splitlines(keepends=True)
    stripped = "".join(l for l in copy_lines if TAG not in l).encode("utf-8")
    ok = (stripped == frozen_bytes)
    print(f"[make_fira_tree_probe] copy md5 {md5_of(copy_bytes)}; verbatim check: stripped md5 {md5_of(stripped)} "
          f"vs frozen {frozen_md5} -> {'PASS' if ok else 'FAIL'}")
    if not ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
