/**
 * @file    dolph_f5_goldens.h
 * @brief   F5-A frozen 8 per-channel core-subband golden CRCs (Dolph-Chebyshev -20dB weighted chirp).
 *
 * Plan : sprint4/dsp/fira/F5_F7_PLAN.md section 1.3 (8 per-channel goldens, extends the F4 sbgold method).
 * L-grade: [L2] (desktop golden + distinctness proof); on-board g_f5_crc_core[c] recomputed live and
 *          compared bit-for-bit -> [L1/EZKIT] closes when the FIRA subband matches per channel.
 *
 * +-----------------------------------------------------------------------------+
 * | WHAT EACH VALUE IS                                                            |
 * |  g_f5_golden_crc[c] = CRC32(IEEE 802.3) of the 4 core subbands (sb0|sb1|sb2|  |
 * |  sb3, that order, every frame; streaming, init 0xFFFFFFFF, final ^0xFFFFFFFF)  |
 * |  produced by the VERBATIM core chain (tree_filterbank.c tfb_analyze) run over  |
 * |  the frozen chirp (chirp_input.h) scaled by channel c's Dolph weight at        |
 * |  INPUT-SCALE: x_weighted_q31 = (int32_t)(((int64_t)w_q15[c]*x_q31) >> 15).      |
 * |  Same CRC method as fira_regression.c crc32_update -> board reads compare       |
 * |  apples-to-apples.                                                            |
 * |                                                                              |
 * | BIT-EXACT BOUNDARY (plan 1.2, section 12 FG1): the WEIGHT IS INSIDE the boundary. |
 * |  Board criterion = "FIRA subband == core subband, both over chirp*w[c]".        |
 * |                                                                              |
 * | FG1 (no false-green): the 8 weights are distinct -> the 8 goldens are pairwise  |
 * |  DISTINCT (verified by the generator's DISTINCT-CHECK, see evidence below).      |
 * |  An unweighted / degenerate table collapses all 8 to 0x2E0D8C6E and FAILS the    |
 * |  check (FG1 double-guard, plan 1.3 / AC-A2, demonstrated with -DF5_GEN_UNWEIGHTED).|
 * +-----------------------------------------------------------------------------+
 *
 * +-----------------------------------------------------------------------------+
 * | F4 CONTINUITY CROSS-CHECK                                                     |
 * |  c=7 (center pair, w=1.0=DOLPH_W8_ONE=32768, unity gain) golden = 0x2E0D8C6E.  |
 * |  That is EXACTLY the F4 single-channel subband golden (F4_BITEXACT_HANDOFF.md   |
 * |  section 2; the F4 channel ran the equal-gain hb63 chain = unity weight). So     |
 * |  the unity-weight F5 channel reproduces the F4 baseline bit-for-bit: the 8-chan  |
 * |  generalization is a strict superset of the verified single-channel result.      |
 * +-----------------------------------------------------------------------------+
 *
 * GENERATION (committed evidence, same-source discipline like fir_coeffs / dolph_w8_q15.h):
 *   Generator : sprint4/dsp/fira/gen_f5_goldens.c (links the verbatim tree_filterbank.c).
 *   Weights   : sprint4/dsp/fira/dolph_w8_q15.h (F5-C frozen, baseline 8b373f3).
 *   Excitation: sprint4/dsp/core_only/bench/chirp_input.h (frozen, same as F0/F4).
 *   DISTINCT-CHECK: all 8 pairwise distinct -> PASS (generator stdout, exit 0).
 *   Negative control (-DF5_GEN_UNWEIGHTED): all 8 collapse to 0x2E0D8C6E -> 28 collisions
 *     -> DISTINCT-CHECK FAILS (proves the check is weight-dependent, not a constant).
 *   Values frozen here; NOT recomputed on board (on board recomputed live for self-check only).
 *
 * ASCII-only. CCES SHARC target (ADSP-21569).
 */
#ifndef ITC_DOLPH_F5_GOLDENS_H
#define ITC_DOLPH_F5_GOLDENS_H

#include <stdint.h>
#include "dolph_w8_q15.h"   /* DOLPH_W8_NCH = 8 */

/* F5-A frozen 8 per-channel core-subband golden CRCs (index = channel c).
 * Generated by gen_f5_goldens.c over chirp * g_dolph_w8_q15[c] (input-scale).
 * Pairwise distinct (FG1). c=7 == 0x2E0D8C6E == F4 unity-weight baseline (continuity). */
static const uint32_t g_f5_golden_crc[DOLPH_W8_NCH] = {
    0x8E807729u,   /* c=0  {0,15} edge    w_q15=28404 (w=0.866829693) */
    0xB2F1E13Fu,   /* c=1  {1,14}         w_q15=16525 (w=0.504310065, min weight) */
    0x7B109C71u,   /* c=2  {2,13}         w_q15=20371 (w=0.621670438) */
    0xD7BD23E7u,   /* c=3  {3,12}         w_q15=24031 (w=0.733379377) */
    0xA000D606u,   /* c=4  {4,11}         w_q15=27287 (w=0.832733104) */
    0x2403E085u,   /* c=5  {5,10}         w_q15=29934 (w=0.913514611) */
    0xB88D91B5u,   /* c=6  {6,9}          w_q15=31802 (w=0.970518658) */
    0x2E0D8C6Eu,   /* c=7  {7,8}  center  w_q15=32768 (w=1.0, unity == F4 baseline golden) */
};

#endif /* ITC_DOLPH_F5_GOLDENS_H */
