/**
 * @file    m2_wtbl_q15.h
 * @brief   S7-SIDE30: runtime-selectable broadside weight tables for M2_WTBL_SEL (NOT frozen).
 *
 * GENERATED by sprint7/dsp/wtbl/gen_m2_wtbl.py -- DO NOT EDIT BY HAND (same-source discipline;
 * `gen_m2_wtbl.py --check` diffs this file against a fresh generation).
 * Basis: DEC-S7-SIDE30-01 (2)(4) (CTO 2026-09-26 agreed to reopen D6 and to firmware changes; that THIS
 *        package falls under it is a PM reading pending CTO review, DEC (4)) and
 *        sprint7/docs/S7_SIDE30_ANALYSIS.md sec 3. Used ONLY under #ifdef M2_WTBL_SEL.
 *
 * sel 0 = the FROZEN g_dolph_w8_q15 (Dolph -20, sprint4/dsp/fira/dolph_w8_q15.h) -- NOT duplicated here.
 * sel k (k=1..M2_WTBL_NEXTRA) = g_m2_wtbl_q15[k-1]. Index c = channel = pair {c,15-c}, edge(0)->centre(7),
 * exactly like the frozen table. Q15 scale 1.0 = 32768 (== DOLPH_W8_ONE); all values <= 32768 (GAP-SAT ok).
 * Dual track (iron rule 7): scipy chebwin vs Barbiere closed form -> bit-identical Q15; generator anchor:
 * reproduces the frozen D20 table bit-exactly. [L2/dual-track desktop]
 *
 * Ideal far-field metrics [L2, isotropic point-source model s7_common.py; NOT board/acoustic readings]:
 *   table  BW(-6)@1k  SLL    att30@500  att30@1k  att90 band-avg 1k/2k/4k   on-axis vs D20  WNGn
 *   D20*    29.27 deg -20.00    5.86    23.10    22.7/ 23.2/ 23.0    +0.00 dB  -0.17
 *   D25     32.18 deg -25.00    4.78    37.81    27.0/ 28.1/ 28.0    -1.02 dB  -0.37
 *   D30     34.87 deg -30.00    4.06    21.78    31.6/ 33.0/ 32.9    -1.82 dB  -0.65
 *   D35     37.36 deg -35.00    3.54    17.11    36.9/ 37.8/ 37.8    -2.47 dB  -0.92
 *   (* D20 = frozen sel 0, listed for reference only)
 * GATING (critic R2 MAJOR-3b): on-board A/B only AFTER polarity QA has measured the channel->position
 * map and the CTO D8 ruling; a deeper table on a mis-mapped array tells you nothing. Table choice waits
 * for the per-driver spread measurement (critic R2 MAJOR-3c).
 */
#ifndef ITC_M2_WTBL_Q15_H
#define ITC_M2_WTBL_Q15_H

#include <stdint.h>

#define M2_WTBL_NEXTRA  3   /* extra tables beyond the frozen sel-0 table */

static const int32_t g_m2_wtbl_q15[M2_WTBL_NEXTRA][8] = {
    { 16080, 13167, 17479, 21793, 25778, 29113, 31512, 32768 },   /* sel 1: Dolph-Chebyshev -25 dB */
    {  9535, 10397, 14932, 19718, 24327, 28300, 31221, 32768 },   /* sel 2: Dolph-Chebyshev -30 dB */
    {  5868,  8179, 12739, 17834, 22954, 27510, 30932, 32768 },   /* sel 3: Dolph-Chebyshev -35 dB */
};

#endif /* ITC_M2_WTBL_Q15_H */
